### ISSUE TITLE
Point lights flicker when you move the camera.

### ISSUE THREAD

**Issue by Fabrazz** [unity3d-jp/UnityChanToonShaderVer2_Project#105]
Great shader, however point & spotlights flicker on the surface for me. This is with the built-in render pipeline using Toon (Built-in) and only occurs in play mode. Any help would be greatly appreciated
![Flickers](https://user-images.githubusercontent.com/3443494/167690540-0a162a40-1006-4c55-a262-91b19ed44917.gif)

**Comment by Fabrazz** [comment]
Update, this happens when meshes are combined during play from being set to static. Any solution to this?
![image](https://user-images.githubusercontent.com/3443494/167718968-53c3643e-2871-45a0-b41a-932b50fca410.png)

**Comment by Nobuyuki-Kobayashi** [comment]
As far as I can judge from the screenshot, I assume you are using UTS2 for background objects in your scene.
UTS2 is a character-specific toon shader, so there must be one real-time directional light in the scene for look design.
If you are using UTS2 for background objects and there is no available directional light in the scene, I strongly recommend using a PBR shader such as Standard Shader.

**Comment by H3idi-X** [comment]
Hi, it looks like the light falls on flat objects. If this assumption is right, I believe this should be  hard to solve,  as UTS clip a light at a certain level.
For flat objects, every single normal on the meshes are completely the same. It brings about sudden change of shading when we move lights, objects or cameras.

**Comment by Nobuyuki-Kobayashi** [comment]
For toon shaders, including UTS2, that use lights to generate paint divisions, the following methods are generally used if you want to moderate the change in the way the lights hit the planes.

1. Instead of dividing the plane into a minimal number of divisions, add several divisions to increase the number of vertices on the plane.
2. Transfer the vertex normals of the sphere or other part of the surface to those vertex normals using the DCC tool.

By doing 1 and 2, you can smooth the light hitting each vertex and thus avoid sudden changes in the painting.
The UTS2 normal map lighting sample does the same thing, so I recommend checking the geometry there.

https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/blob/release/legacy/2.0/Manual/UTS2_Manual_en.md#normalmap-settings-submenu

Check a ※Hint section above.

Any further usage is beyond the scope of our support, so please investigate on your own.

**Comment by H3idi-X** [comment]
Hi, If we do not receive additional information, we will close this issue in a few days. We have set up a template for bug reports, so please fill it the next time you wish to submit a bug report.
