### ISSUE TITLE
How could we upgrade SD Kohakuchanz material properly?

### ISSUE THREAD

**Issue by Thaina** [unity3d-jp/UnityChanToonShaderVer2_Project#118]
Since there is this package SDKohakuchanz from 2016 https://unity-chan.com/download/releaseNote.php?id=SDKohakuchanz that using outdated built-in material, unlike other package (SD Tokochanz https://unity-chan.com/download/releaseNote.php?id=SD_Toko and other similar package released in the same time at 2019). When we switch to this repo's shader it give me weird lighting effect like this

![image](https://user-images.githubusercontent.com/1042507/205500981-6df395d2-ea71-4288-af6f-7b3852f9121a.png)

I can't find newer version of this package and cannot find a way to properly upgrade these material. It seem the format of texture and material (of 2016) was also not the same as newer version (2019)

So is it possible to create new package for these model or have a script to upgrade the old material into newer version? Or is there an updated package I could downloaded from?

**Comment by H3idi-X** [comment]
We checked the site.
They are not UTS at all and it's not UTS issue.

**Comment by Thaina** [comment]
@H3idi-X Right, if it not UTS then what happening to unitychan package before UTS though?

**Comment by H3idi-X** [comment]
This is the place to talk about shader issues. As to  Unity-chan web contents, will you please contact with Unity-chan web site?

**Comment by Thaina** [comment]
I am sincerely apologize but because there is material upgrade option in this package so I wonder why it didn't work with the official unitychan material

**Comment by Nobuyuki-Kobayashi** [comment]
Hi Thaina-san

There seem to be a few misunderstandings, so let me clear them up once and for all.
First of all, the shaders and materials used in the SD-KohakuchanZ model you asked about are not using UTS2, but a completely different shader from UTS2.
The UTS Converter can only be used with UTS2 materials, so you will need to port the materials for the SD-KohakuchanZ model by yourself.
Some of the older shaders are used in the official Unity-chan download area.
The shaders used for each model are supposed to be used as they are, so if you need to change them to other shaders, please try to search for information on the Internet.
The following Youtube movie may be helpful, although the captions are in Japanese.

UTS2: SD Unity-Chan Material Setup
https://www.youtube.com/watch?v=qDAo5gqIezw

Comparison of Unity-Chan shader and UTS2 v.2.0.5
https://www.youtube.com/watch?v=A7y48JQM7SQ

Since UTS2 and UTS are almost identical in terms of shader functionality, I believe you can set up with UTS using the above as a reference.

If you have any questions about the downloadable items on Unity-chan's official website, please contact unity-chan@unity3d.com.

**Comment by Thaina** [comment]
Thank you very much for your clarification
