### ISSUE TITLE
Shader error in 'Universal Render Pipeline/Toon': maximum ps_4_0 sampler register index (16) exceeded at Assets/ToonRendering/Toon(Universal)/Shaders/UniversalToonBody.cginc(109) (on d3d11)

### ISSUE THREAD

**Issue by 0risin** [unity3d-jp/UnityChanToonShaderVer2_Project#40]
Shader error in 'Universal Render Pipeline/Toon': maximum ps_4_0 sampler register index (16) exceeded at Assets/ToonRendering/Toon(Universal)/Shaders/UniversalToonBody.cginc(109) (on d3d11)

Compiling Fragment program with _METALLICSPECGLOSSMAP _OCCLUSIONMAP _MAIN_LIGHT_SHADOWS _NORMALMAP _ENVIRONMENTREFLECTIONS_OFF _EMISSIVE_SIMPLE _IS_TRANSCLIPPING_OFF _IS_ANGELRING_OFF _IS_PASS_FWDBASE _IS_CLIPPING_OFF
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_RGBM_ENCODING

**Comment by Nobuyuki-Kobayashi** [comment]
Hi, 0risin.

Thank you very much for sharing your experience with us. We always appreciate the opportunity to engage with users as we endeavor to improve the quality of our products to meet the needs of users.

After careful consideration, we will be closing this particular ticket. 

However, we would like to offer the following suggestions so that we have the appropriate information to act on any issues that may arise in the future. 

- What are the specs of the PC being used, and under what circumstances did this issue arise?
- Can the issue be reproduced? If so, under what circumstances specifically? 
- Can the issue be explained in clear, concise terms? 

We certainly hope that you will continue to use our products in the future. 
Best Regards,
Nobu
