### ISSUE TITLE
Shader Sampler Exeption, when adding to Shader to Material (Model in description)

### ISSUE THREAD

**Issue by 0risin** [unity3d-jp/UnityChanToonShaderVer2_Project#43]
Hello,

when selecting 'Universal Render Pipeline/Toon' as shader for the attached model, I get the following exception in the Unity Console.
[Hilde.zip](https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/files/4416130/Hilde.zip)

I'm using URP in my Project.
```
Shader error in 'Universal Render Pipeline/Toon': maximum ps_4_0 sampler 


register index (16) exceeded at Assets/ToonRendering/Toon(Universal)/Shaders/UniversalToonBody.cginc(109) (on d3d11)

Compiling Fragment program with _METALLICSPECGLOSSMAP _OCCLUSIONMAP _MAIN_LIGHT_SHADOWS _NORMALMAP _ENVIRONMENTREFLECTIONS_OFF _EMISSIVE_SIMPLE _IS_TRANSCLIPPING_OFF _IS_ANGELRING_OFF _IS_PASS_FWDBASE _IS_CLIPPING_OFF
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_RGBM_ENCODING
```
Specs are:
AMD Ryzen 2600X
GeForce RTX 2070
16 GB RAM
![image](https://user-images.githubusercontent.com/7229990/78154716-de9e5680-743c-11ea-8255-8b3be452eea2.png)
![image](https://user-images.githubusercontent.com/7229990/78154791-f544ad80-743c-11ea-91be-5baee6f7ac64.png)

Greetings Orisin

**Comment by Nobuyuki-Kobayashi** [comment]
Hi, 0risin, thank you for your issue.
UTS2/UniversalToon is the internal test phase now, so we don't provide support to solve your problem.

On the other hand, many cases would be fixed by updating your UTS2/UniversalToon to the latest one. If you try it, remove the folder where UTS2/UniversalToon files are installed from your Assets folder, and install the latest package from the link below.
https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/blob/urp/master/UTS2URP_ShaderOnly_v8.0.0.unitypackage

After that, if you tell us more information like below, it might help us to solve some problems which could be hiding.
1. The version of Unity in which you have found this problem.
2. The version of Universal RP in which you have found this problem.
3. Test the sample projet from the link below, and tell us whether every sample projects work well with your PC.
https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/archive/urp/master.zip
