### ISSUE TITLE
 srp batcher compitable?

### ISSUE THREAD

**Issue by mdm123** [unity3d-jp/UnityChanToonShaderVer2_Project#49]
I have checked urp branch.unfortunately,it doesn't support srp batcher now.Do you have a plan for this?

**Comment by daotianxianyu** [comment]
Look forward to SRP batcher's support

**Comment by H3idi-X** [comment]
I don't believe SRP batcher can be ignored inside shader. Can you elaborate that?

**Comment by Kulgann** [comment]
> I don't believe SRP batcher can be ignored inside shader. Can you elaborate that?

The properties used in the shader are not put in the correct CBUFFERS thus making the shader not compatible with the SRP batcher. Im currently atempting to put all properties from the body part of the shader in the right buffers. Will update if I manage to get it to work.

Edit: End of the day I did manage to get the shader to be compatible with the SRP batcher, but the outline pass had to be dropped and it required a significant rewrite of some of the files Mainly droping the LitInput includes and moving everything to a new ToonInput

**Comment by H3idi-X** [comment]
Hi, Apology  for my misunderstanding. We've succeed to make Unity Toon Shader compatible with SRP Batcher. We'll back port it to Universal Toon Shader as soon as possible.

**Comment by H3idi-X** [comment]
Hi, We released Universal Toon Shader 2.3.0, which is compatible with SRP Batcher.
There are some you might want to keep in mind:
- Most of the cases, UTS materials draw Outline Pass. in these cases SPR batcher is canceled. Because it is not compatible with multi pass rendering.
- When drawing some meshes, If shader keywords are different from each other, SRP batcher is canceled.
- MaterialPropertyBlock cancels a whole forward pass SPR Batcher, you should refrain from using this feature when want to take advantage of SRP bather.

Thanks,
UTS Team.
