### ISSUE TITLE
What is the difference between Toon_DoubleShadeWithFeather and Toon_DoubleShadeWithFeather_Mobile?

### ISSUE THREAD

**Issue by ryoogood** [unity3d-jp/UnityChanToonShaderVer2_Project#72]
Hi.
I am using unitychanToonShader well.
I have a question and ask a question.
What is the difference between Toon_DoubleShadeWithFeather and Toon_DoubleShadeWithFeather_Mobile?
I've tried using it, and both work the same.
Could someone please explain the specific difference?

Mobile has UsePass in the last line, but it is the same as Toon_DoubleShadeWithFeather.
 
Thanks for serving unitychan.

**Comment by Nobuyuki-Kobayashi** [comment]
Thank you for your inquiry.

Each shader in the UTS2 mobile version omits the FORWRD_DELTA pass.
This pass functionally handles the toon processing of the real-time point light, but since the real-time point light itself is a heavy function in the mobile environment, we have omitted this pass to reduce the task of shaders.

Regards,
Nobu
