### ISSUE TITLE
Unable to install shader to the package manager

### ISSUE THREAD

**Issue by IzzyDev05** [unity3d-jp/UnityChanToonShaderVer2_Project#93]
For reference, I'm using Unity 2020.3
This is my first time installing an asset pack from Github, so my apologies if this is a dumb question. I installed Git on my pc and went to the package manager > Add package from Git URL > Pasted this URL into the field "_https://github.com/Unity-Technologies/com.unity.toonshader.git_"
However, I'm getting an error saying that this URL does not point to a valid package repository (Log image attached). Could someone help me out? 

Thank you!

![image](https://user-images.githubusercontent.com/66153582/134103655-4969c34a-6426-4c11-9c10-f86ed278ec98.png)

**Comment by riina** [comment]
You have to format it differently, for example using `https://github.com/Unity-Technologies/com.unity.toonshader.git?path=/com.unity.toonshader#0.2.0-preview`

The `0.2.0-preview` is one of the git tags in the repo. It can be replaced with any tag or the short sha hash you see for any commit.

You need the `path=/com.unity.toonshader` part because the actual package contents are stored in a sub directory of the repository.

Hope this helps!

**Comment by IzzyDev05** [comment]
@riina Thank you so much for the help, it's working now!

**Comment by riina** [comment]
Nice!

Once issues are resolved on github, you ought to close the issue to mark it as solved~
